### ISSUE TITLE
Confirm whitelist vs. blacklist options for Redux data in local storage

### ISSUE THREAD

**Issue by corquaid** [Altalogy/tari#218]
Follow-on issue from #40:

**Tom:** I'm wondering whether the whitelist would be a better option... whitelist is safer, but blacklist is more convenient. Also, whitelist decreases a chance that we will store large amount of data.
I could not find any information about restrictions on the localStorage size in Tauri, usually it is about 10 Mb in web browsers.

**Tarnas:** yes, whitelist is safer, but I was lazy, we can come back to it and check it again, there's a possibility that once we start to collect performance stats etc. we'll have to revisit this and change the way we persist store, but it's a small change we can always do

**Comment by tomaszantas** [comment]
Reviewed this concern and the localStorage data:
- credentials are not present in the localStorage (wallet password and merged/monero authentication)
- due to small number of credentials used in the app, and dedicated Redux store: `credentials` that is blacklisted, the blacklist approach is more convenient.
